//
//  Constants.h
//  MeshStremingiOSClient
//
//  Created by Xu Haiyang on 11/27/12.
//  Copyright (c) 2012 Xu Haiyang. All rights reserved.
//

#import <Foundation/Foundation.h>

@interface Constants : NSObject

FOUNDATION_EXPORT NSString *const DEFAULT_HOST;
FOUNDATION_EXPORT NSString *const DEFAULT_PORT;
FOUNDATION_EXPORT NSString *const SERVER_STATE_NOT_CONNECTED;
FOUNDATION_EXPORT NSString *const SERVER_STATE_CONNECTED;
FOUNDATION_EXPORT NSString *const BUTTON_TEXT_CONNECT;
FOUNDATION_EXPORT NSString *const BUTTON_TEXT_DISCONNECT;

enum SOCKET_STATE {SOCKET_CONNECTED_IDLE, SOCKET_NOT_CONNECTED_IDLE, SOCKET_WAIT_FOR_MODEL_LIST_SIZE , SOCKET_WAIT_FOR_MODEL_LIST};

FOUNDATION_EXPORT NSString *const COMMAND_REQUEST_MODEL_LIST_XML;

FOUNDATION_EXPORT NSString *const COMMAND_REQUEST_MODEL_LIST_XML_SIZE;

@end
